const PORT = 3000;
const HOST = '127.0.0.1';
const MONGO_URI = 'mongodb://localhost:27017/planzvit';
const BCRYPT_SALT = 10;
const JWT_ACCESS_SECRET = 'PLANZVIT-JWT-ACCESS-SECRET';
const JWT_ACCESS_EXPIRES_IN = '15m';
const JWT_REFRESH_SECRET = 'PLANZVIT-JWT-REFRESH-SECRET';
const JWT_REFRESH_EXPIRES_IN = '7d';

export default () => ({
  HOST: process.env.HOST || HOST,
  PORT: parseInt(process.env.PORT, 10) || PORT,
  MONGO_URI: process.env.MONGO_URI || MONGO_URI,
  BCRYPT_SALT: parseInt(process.env.BCRYPT_SALT, 10) || BCRYPT_SALT,
  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET || JWT_ACCESS_SECRET,
  JWT_ACCESS_EXPIRES_IN: process.env.JWT_ACCESS_EXPIRES_IN || JWT_ACCESS_EXPIRES_IN,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET || JWT_REFRESH_SECRET,
  JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN || JWT_REFRESH_EXPIRES_IN
});
